# Generated by Django 4.1.5 on 2023-01-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=16)),
                ('area_surface', models.FloatField()),
                ('area_frontal', models.FloatField()),
                ('dry_coef0', models.FloatField()),
                ('dry_coef1', models.FloatField()),
                ('dry_coef2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaporator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=16)),
                ('area_surface', models.FloatField()),
                ('area_frontal', models.FloatField()),
                ('min_airflow', models.FloatField()),
                ('max_airflow', models.FloatField()),
                ('dry_c0', models.FloatField()),
                ('dry_c1', models.FloatField()),
                ('dry_c2', models.FloatField()),
                ('wet_c0', models.FloatField()),
                ('wet_c1', models.FloatField()),
                ('wet_c2', models.FloatField()),
                ('wet_c3', models.FloatField()),
                ('wet_c4', models.FloatField()),
                ('wet_c5', models.FloatField()),
                ('wet_c6', models.FloatField()),
                ('wet_c7', models.FloatField()),
                ('wet_c8', models.FloatField()),
            ],
        ),
    ]
