# Generated by Django 4.1.5 on 2023-01-13 03:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condenser',
            name='dry_coef0',
        ),
        migrations.RemoveField(
            model_name='condenser',
            name='dry_coef1',
        ),
        migrations.RemoveField(
            model_name='condenser',
            name='dry_coef2',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='dry_c0',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='dry_c1',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='dry_c2',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c0',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c1',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c2',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c3',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c4',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c5',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c6',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c7',
        ),
        migrations.RemoveField(
            model_name='evaporator',
            name='wet_c8',
        ),
        migrations.AddField(
            model_name='condenser',
            name='dry_c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=3),
        ),
        migrations.AddField(
            model_name='evaporator',
            name='dry_c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=3),
        ),
        migrations.AddField(
            model_name='evaporator',
            name='wet_c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=9),
        ),
    ]
