# Generated by Django 4.1.5 on 2023-01-13 03:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0002_remove_condenser_dry_coef0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=16)),
                ('refrigerant', models.CharField(max_length=10)),
                ('voltage', models.IntegerField()),
                ('subcool', models.FloatField()),
                ('superheat', models.FloatField()),
                ('volume', models.FloatField()),
                ('capacity_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('power_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('supply_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('massflow_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=32)),
                ('rpm_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('power_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('current_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
            ],
        ),
    ]
