# Generated by Django 4.1.5 on 2023-01-13 04:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0003_compressor_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='current_c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=9),
        ),
        migrations.AlterField(
            model_name='fan',
            name='power_c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=9),
        ),
        migrations.AlterField(
            model_name='fan',
            name='rpm_c',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=9),
        ),
    ]
