# Generated by Django 4.1.5 on 2023-01-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0004_alter_fan_current_c_alter_fan_power_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressor',
            old_name='capacity_c',
            new_name='capacity_coefficient',
        ),
        migrations.RenameField(
            model_name='compressor',
            old_name='massflow_c',
            new_name='massflow_coefficient',
        ),
        migrations.RenameField(
            model_name='compressor',
            old_name='power_c',
            new_name='power_coefficient',
        ),
        migrations.RenameField(
            model_name='compressor',
            old_name='supply_c',
            new_name='supply_coefficient',
        ),
        migrations.RenameField(
            model_name='condenser',
            old_name='dry_c',
            new_name='dry_coefficient',
        ),
        migrations.RenameField(
            model_name='evaporator',
            old_name='dry_c',
            new_name='dry_coefficient',
        ),
        migrations.RenameField(
            model_name='evaporator',
            old_name='wet_c',
            new_name='wet_coefficient',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='current_c',
            new_name='current_coefficient',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='power_c',
            new_name='power_coefficient',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='rpm_c',
            new_name='rpm_coefficient',
        ),
    ]
