# Generated by Django 4.1.5 on 2023-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0005_rename_capacity_c_compressor_capacity_coefficient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowOrientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_orientaion', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
