# Generated by Django 4.1.5 on 2023-01-13 08:52

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0006_floworientation_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='condenser',
            field=models.ManyToManyField(blank=True, related_name='condenser', to='selecting.condenser'),
        ),
        migrations.AddField(
            model_name='unit',
            name='f7_static_coefficient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=3),
        ),
        migrations.AddField(
            model_name='unit',
            name='flow_direction',
            field=models.ManyToManyField(blank=True, related_name='unit', to='selecting.floworientation'),
        ),
        migrations.AddField(
            model_name='unit',
            name='g4_static_coefficient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=3),
        ),
        migrations.AddField(
            model_name='unit',
            name='model',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_fan',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
