# Generated by Django 4.1.5 on 2023-01-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0007_unit_condenser_unit_f7_static_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='compressor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compressor', to='selecting.compressor'),
        ),
        migrations.AddField(
            model_name='unit',
            name='evaporator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaporator', to='selecting.evaporator'),
        ),
    ]
