# Generated by Django 4.1.5 on 2023-01-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0008_unit_compressor_unit_evaporator'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='default_airflow',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan', to='selecting.fan'),
        ),
    ]
