# Generated by Django 4.1.5 on 2023-01-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0009_unit_default_airflow_unit_fan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compressor',
            old_name='supply_coefficient',
            new_name='current_coefficient',
        ),
        migrations.AlterField(
            model_name='unit',
            name='flow_direction',
            field=models.ManyToManyField(blank=True, related_name='flow', to='selecting.floworientation'),
        ),
    ]
