# Generated by Django 4.1.5 on 2023-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0010_rename_supply_coefficient_compressor_current_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressor',
            name='evap_temp_limit',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
    ]
