# Generated by Django 4.1.5 on 2023-02-27 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0011_compressor_evap_temp_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='capacity_coefficient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=24),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='current_coefficient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=24),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='massflow_coefficient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=24),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='power_coefficient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=24),
        ),
    ]
