# Generated by Django 4.1.5 on 2023-03-06 03:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0014_evaporator_starting_dewpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaporator',
            name='starting_dewpoint',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=-1, size=7),
        ),
    ]
