# Generated by Django 4.1.5 on 2023-03-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0015_alter_evaporator_starting_dewpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='condenser',
            name='airflow_m3hr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
