# Generated by Django 4.1.5 on 2023-05-23 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0016_condenser_airflow_m3hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='number_of_compressor',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
