# Generated by Django 4.1.5 on 2023-06-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0017_unit_number_of_compressor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='compressor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compressor', to='selecting.compressor'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='evaporator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='evaporator', to='selecting.evaporator'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fan', to='selecting.fan'),
        ),
    ]
