# Generated by Django 4.1.5 on 2023-06-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0019_unit_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_cart', models.BooleanField()),
                ('inlet_temp', models.FloatField()),
                ('inlet_rh', models.FloatField()),
                ('airflow', models.PositiveIntegerField()),
                ('esp', models.PositiveIntegerField()),
                ('amb_temp', models.FloatField()),
                ('filter', models.CharField(max_length=3)),
                ('comp_spd', models.PositiveIntegerField()),
                ('total_cap', models.FloatField()),
                ('sen_cap', models.FloatField()),
                ('fan_power', models.FloatField()),
                ('fan_rpm', models.PositiveIntegerField()),
                ('tsp', models.IntegerField()),
                ('t_evap', models.FloatField()),
                ('t_cond', models.FloatField()),
                ('off_temp', models.FloatField()),
                ('off_rh', models.FloatField()),
                ('outlet_temp', models.FloatField()),
                ('outlet_rh', models.FloatField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comp', to='selecting.compressor')),
                ('cond', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cond', to='selecting.condenser')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='unit', to='selecting.unit')),
            ],
        ),
    ]
