# Generated by Django 4.1.5 on 2023-06-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0020_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='size',
            field=models.IntegerField(default=500, max_length=4),
            preserve_default=False,
        ),
    ]
