# Generated by Django 4.1.5 on 2023-06-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0021_fan_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='hp',
            field=models.IntegerField(default=5, max_length=2),
            preserve_default=False,
        ),
    ]
