# Generated by Django 4.1.5 on 2023-06-20 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0022_unit_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='hp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
