# Generated by Django 4.1.5 on 2023-06-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0024_remove_unit_hp_compressor_hp_alter_fan_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='flow_orientaion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='selecting.floworientation'),
            preserve_default=False,
        ),
    ]
