# Generated by Django 4.1.5 on 2023-06-20 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0025_calculation_flow_orientaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 12, 51, 35, 974338)),
        ),
    ]
