# Generated by Django 4.1.5 on 2023-06-21 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0027_alter_calculation_date_time_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 11, 21, 41, 435965)),
        ),
    ]
