# Generated by Django 4.1.5 on 2023-06-22 09:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selecting', '0028_series_image_alter_calculation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 17, 45, 4, 421093)),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date_time', models.DateTimeField(default=datetime.datetime(2023, 6, 22, 17, 45, 4, 422092))),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='selecting.calculation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
