# Generated by Django 4.1.5 on 2023-06-26 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0029_alter_calculation_date_time_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 10, 21, 13, 790810)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 10, 21, 13, 790810)),
        ),
    ]
