# Generated by Django 4.1.5 on 2023-06-26 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0030_motortype_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='type',
            field=models.CharField(choices=[(1, 'AC'), (2, 'EC'), (3, 'DC'), (4, 'BD')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 10, 25, 46, 661261)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 10, 25, 46, 661261)),
        ),
    ]
