# Generated by Django 4.1.5 on 2023-06-26 03:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0032_alter_calculation_date_time_alter_fan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='depth',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(4000)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='height',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(4000)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='length',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(4000)]),
        ),
        migrations.AddField(
            model_name='unit',
            name='power_supply',
            field=models.CharField(default='400V-3ph-50Hz', max_length=13),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 11, 55, 20, 989993)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 11, 55, 20, 990531)),
        ),
    ]
