# Generated by Django 4.1.5 on 2023-06-26 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0033_unit_depth_unit_height_unit_length_unit_power_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='heat_rejection',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 12, 39, 7, 635781)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 12, 39, 7, 638821)),
        ),
    ]
