# Generated by Django 4.1.5 on 2023-06-28 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0036_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floworientation',
            name='discharge_orientation',
            field=models.CharField(default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 14, 59, 13, 996161)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 14, 59, 13, 997158)),
        ),
    ]
