# Generated by Django 4.1.5 on 2023-07-13 09:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0042_remove_fan_type_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'AC'), (2, 'EC'), (3, 'DC'), (4, 'BD')], default=1, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 17, 55, 48, 888986)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 17, 55, 48, 891893)),
        ),
    ]
