# Generated by Django 4.1.5 on 2023-10-03 09:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0046_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressor',
            name='capacity_factor',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 17, 2, 37, 431414)),
        ),
        migrations.AlterField(
            model_name='fan',
            name='type',
            field=models.PositiveIntegerField(choices=[(2, 'EC'), (3, 'DC'), (4, 'BD'), (1, 'AC')], validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 17, 2, 37, 431414)),
        ),
    ]
