# Generated by Django 4.1.5 on 2023-11-03 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0048_unit_arrange_id_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChillwaterCoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 41, 31, 562433)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 41, 31, 563430)),
        ),
    ]
