# Generated by Django 4.1.5 on 2023-11-03 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0050_chillwatercoil_uh_model_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 53, 57, 889143)),
        ),
        migrations.AlterField(
            model_name='chillwatercoil',
            name='uh_model',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cwmodel'),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 53, 57, 891139)),
        ),
    ]
