# Generated by Django 4.1.5 on 2023-11-06 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0053_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chillwatercoil',
            old_name='uh_model',
            new_name='dp_model',
        ),
        migrations.AddField(
            model_name='chillwatercoil',
            name='mdry_model',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cwmodel'),
        ),
        migrations.AddField(
            model_name='chillwatercoil',
            name='mdwet_model',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cwmodel'),
        ),
        migrations.AddField(
            model_name='chillwatercoil',
            name='udry_model',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cwmodel'),
        ),
        migrations.AddField(
            model_name='chillwatercoil',
            name='uwet_model',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cwmodel'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 15, 22, 30, 206972)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 15, 22, 30, 211958)),
        ),
    ]
