# Generated by Django 4.1.5 on 2023-11-10 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0054_rename_uh_model_chillwatercoil_dp_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillwatercoil',
            name='starting_dewpoint',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cwmodel'),
        ),
        migrations.AddField(
            model_name='unit',
            name='cw_coil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cw_coil', to='selecting.chillwatercoil'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 43, 38, 377749)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 43, 38, 386472)),
        ),
    ]
