# Generated by Django 4.1.5 on 2023-11-30 02:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0055_chillwatercoil_starting_dewpoint_unit_cw_coil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 10, 48, 16, 284701)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 10, 48, 16, 286696)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='compressor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compressor', to='selecting.compressor'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='cw_coil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cw_coil', to='selecting.chillwatercoil'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='evaporator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='evaporator', to='selecting.evaporator'),
        ),
    ]
