# Generated by Django 4.1.5 on 2023-12-06 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0056_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chillwatercoil',
            old_name='mdwet_model',
            new_name='mwet_model',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 11, 15, 50, 591554)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 11, 15, 50, 595543)),
        ),
    ]
