# Generated by Django 4.1.5 on 2023-12-06 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0057_rename_mdwet_model_chillwatercoil_mwet_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillwatercoil',
            name='area_frontal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chillwatercoil',
            name='area_surface',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chillwatercoil',
            name='max_airflow',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chillwatercoil',
            name='min_airflow',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 14, 25, 14, 215460)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 14, 25, 14, 215460)),
        ),
    ]
