# Generated by Django 4.1.5 on 2024-01-03 08:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0058_chillwatercoil_area_frontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='default_comp_speed',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 44, 49, 770268)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 44, 49, 771991)),
        ),
    ]
