# Generated by Django 4.1.5 on 2024-01-05 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0059_unit_default_comp_speed_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='image',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 14, 43, 48, 223886)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 14, 43, 48, 227875)),
        ),
    ]
