# Generated by Django 4.1.5 on 2024-01-05 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecting', '0060_remove_series_image_alter_calculation_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 14, 51, 5, 307762)),
        ),
        migrations.AlterField(
            model_name='history',
            name='generated_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 14, 51, 5, 310301)),
        ),
    ]
